### PR TITLE
Comment out comments in platformio.ini

### PR DESCRIPTION
**Pull request by aj3t4m**

### CODE REVIEW

**Comment by luc-github** [comment]
Thank you but it is currently done on purpose 
the flash mode configuration is not yet implemented in configurator so I left to default some esp32 actually only support 160MHz and other need different flash mode like opi

image

That is why these setting are in comment to let user to change if needed if default used by platformio are not working
I need to find some time to implement them in configurator for esp32 according version

**Comment by aj3t4m** [comment]
This commit only comments out real comments "set frequency to 240MHz" is not an ini setting but a comment.
Without that for some configurations you get broken ini file.

**Comment by luc-github** [comment]
ho boy why I cannot read that properly?
my comment is non sense sorry ....need coffee...

**Comment by luc-github** [comment]
@all-contributors please add @aj3t4m for bug fix

**Comment by luc-github** [comment]
@all-contributors please add @aj3t4m for code fix also

**Pull request merged**
